# Generated by Django 5.1.3 on 2024-11-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2024-11-19'),
            preserve_default=False,
        ),
    ]
